### ISSUE TITLE
wget command to fetch files returns 503 from the web server

### ISSUE THREAD

**Issue by SkaBob42** [censusreporter/census-postgres#13]
The wget command in the documentation (wget --recursive --no-parent --accept zip "http://www2.census.gov/acs2010_5yr/summaryfile/2006-2010_ACSSF_By_State_All_Tables/") is no longer functional. The URL will direct you to a page with a directory listing of the files if you navigate there with a web browser, and can be modified to accommodate other years of census data, but when actually running the wget command you will receive a 503 from the web server as-is, and a 302 followed by a 503 if you remove the quotes around the URL.

**Comment by SkaBob42** [comment]
Looks like the issue is something badly misconfigured on the census data web server, so I'm going to close this issue. Even trying to wget a specific file from the server returns the same error, and viewing the output from the server with curl shows "Service Unavailable - DNS failure". Nothing to do on your end, unless you happen to have some way to contact the census folks, and mention that their server is behaving badly...

**Comment by iandees** [comment]
Yep, they have a rather annoying firewall/bot detection system that will block too many wget's. It sounds like you've gotten yourself blocked for a while, but if you [forge wget's User Agent header](https://stackoverflow.com/questions/17182553/sites-not-accepting-wget-user-agent-header) it should help a little bit

**Comment by SkaBob42** [comment]
Thanks for the info. Seems even with a forged user agent it 302's, then 404's on the redirect when done via wget from a host I have on a different external IP. I'll just download the files I need via browser, and scp them to the server, I guess...
